### ISSUE TITLE
login template resets page when clicking on the login button

### ISSUE THREAD

**Issue by sashang** [SAFE-Stack/SAFE-template#184] opened 2018-11-12 13:20 UTC
Hi all - if I create a project like this :

```
dotnet new SAFE -lang F# --layout fulma-login --force
```

a client.fs file is created with username, password and a login button all in a html form. When i hit 'login' I think it submits a POST (do forms automtically generate POST messages?) and seems to reinitialize the page? Why is this? If i remove the html form and handle the OnClick event I get better results

I've created a stripped down version of the template  that demos this behaviour here: https://github.com/sashang/safe-form-post-thing
you should be able to clone and build it useing fake build --target run and then click the button to see the page reset.

If I remove the html form (so the button and username field are no longer in the form) and change props to this 

```
let props = [ RequestProperties.Method HttpMethod.POST Fetch.requestHeaders [ HttpRequestHeaders.ContentType "application/json" ] RequestProperties.Body !^body ]
```

i.e. manually add the POST method it works the way I want it. So I'm wondering why the template has the login button in a form?

**Comment by theimowski** [comment] 2018-11-19 12:36
Hi, thank you for submitting this issue.
Indeed I think that by default browsers treat buttons inside a form element as triggers for sending a request to server.

As this is just a layout template, and is supposed to be adjusted by the user just after creating the project, I don't consider this to be a major issue.
In fact, by employing the bulma templates, I tried to copy them in their original form - if you go to https://dansup.github.io/bulma-templates/templates/login.html which is a preview for the original template, you can see that clicking the button has exactly the same behavior.

Because of that, I'll close this issue and treat this as "by design"

**Closed by theimowski** 2018-11-19 12:36 UTC
