### ISSUE TITLE
Invalid string length during bundle

### ISSUE THREAD

**Issue by omarmrivas** [SAFE-Stack/SAFE-template#346] opened 2020-04-04 20:44 UTC
I have got an Invalid string length error during the bundling process in my project file. Sorry I could not minimize the project to generate the error. The error seems to come from the Client side of the web application.

ℹ ｢wdm｣: wait until bundle finished: /
readline.js:449
    string = this._line_buffer + string;
                               ^

RangeError: Invalid string length
    at Interface._normalWrite (readline.js:449:32)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

[ASPMv2-master.zip](https://github.com/SAFE-Stack/SAFE-template/files/4432460/ASPMv2-master.zip)

**Comment by theimowski** [comment] 2020-04-06 19:55
Not sure what the root cause can be. I can see you created corresponding issue in [Fable repository](https://github.com/fable-compiler/Fable/issues/2007) 
Likely it has something to do with nodejs [limits](https://github.com/nodejs/help/issues/1061), I could reproduce your issue - fable noticeably slowed down while processing following `fable: Compiled .fable/Fable.SimpleJson.3.8.1/Parser.fs`

**Comment by theimowski** [comment] 2020-09-24 09:40
Closing - there's an issue in Fable https://github.com/fable-compiler/Fable/issues/2007 to track

**Closed by theimowski** 2020-09-24 09:40 UTC
