### ISSUE TITLE
Template is not debuggable by default.

### ISSUE THREAD

**Issue by OnurGumus** [SAFE-Stack/SAFE-template#96] opened 2018-05-24 03:04 UTC
If you open the project VS code and from Debug menu start debugging, it will ask you to create configuration files.

If you go to F# tab and select server and then click manually debugging won't start because Client/public path is not compatible with this scenario

**Comment by theimowski** [comment] 2018-05-24 20:30
Right, this is what I'm struggling with as well - not really debugging specifically, but generally because of the nature of the template and all the `//#if` instructions etc. 
It's not adjusted for good tooling support, so any suggestions how that experience could be improved are very welcome

**Comment by isaacabraham** [comment] 2018-05-27 17:18
I think we're talking about two separate things here - the OP is taking about debugging applications created by the template, I think?

**Comment by theimowski** [comment] 2018-05-27 18:48
Ah my bad! Yeah that would be great to add to the template as well. [this](https://github.com/fable-compiler/fable-templates/issues/7) might be a good reference

**Comment by isaacabraham** [comment] 2018-10-03 15:51
I'm looking at this. There's a few things that need doing but I think this is possible. The biggest issue I'm finding right now is seeing how the SAFE template and the Fable template differ in terms of the way that sourcemaps work. I don't know if this is because the Fable template uses an older version of WebPack (3.x rather than 4.x) but the Fable template works "out of the box" with e.g. Chrome debugging extension for Code, but I can't get it working with the SAFE template. cc @alfonsogarciacaro @forki

**Comment by alfonsogarciacaro** [comment] 2018-10-03 21:36
If this is about debugging Fable code directly in VS Code, there's some configuration needed for that. I've managed to do it a couple of times, but then I always forget how I did it later. I usually use the browser dev tools directly (you can use `assert false` in F# to stop the debugger). Maybe [this article](https://medium.com/acoolthingilearned/vs-code-chrome-debugger-and-webpack-10b5e3618d05) helps?

**Comment by isaacabraham** [comment] 2018-10-03 21:59
I'm still fighting with this. I've actually gotten the Code side sorted (the Fable template was a great starting point for this) - using a compound Launch item to build, launch and debug both server and client in the same Code instance. The issue is around the source maps for the client. I think a few things have changed between Fable template and SAFE:

1. The Fable one uses WebPack 3.x whilst SAFE Template uses v4 (which also affects the Code build task background parsing), but for some reason whilst source maps looks pretty rock solid in the Fable Template, I'm stuck with the SAFE one.
2. I've actually frankensteined the Fable one and ported it into a SAFE app of mine which *sort of* gives me source map debugging, but the breakpoints are really inconsistent - sometimes they don't get hit at all.
3. I'm also at a loss as to "how" the browser determines where the source .fs file lives in the debugging tree view.

Perhaps a screen share with someone for 15-30 minutes would help me get over this?

**Comment by theimowski** [comment] 2018-10-04 08:42
It'd be super awesome to have the debugging work for both server and client side at the same time

**Comment by isaacabraham** [comment] 2018-10-06 16:11
@theimowski @OnurGumus @alfonsogarciacaro https://github.com/SAFE-Stack/SAFE-template/pull/161 can you review that? It's not quite there yet, and source maps don't work properly on the client side, but the basic plumbing is there now I think.

**Comment by isaacabraham** [comment] 2018-11-19 13:59
@OnurGumus can you try this again using that PR branch? It should work now.

**Comment by theimowski** [comment] 2018-11-20 12:37
Closed by #161

**Closed by theimowski** 2018-11-20 12:37 UTC
Labels: Status: In Progress, Type: Enhancement
