### ISSUE TITLE
Code formatting

### ISSUE THREAD

**Issue by juselius** [SAFE-Stack/SAFE-template#293] opened 2019-07-10 14:28 UTC
We (*) would like to raise a discussion regarding the code formatting scheme used with the HTML-combinators in the Client code. We find that the current formatting is somewhat cumbersome, impractical and at times hard to read (the same also applies to other Fulma examples):

```fsharp 
div []
        [ Navbar.navbar [ Navbar.Color IsPrimary ]
            [ Navbar.Item.div [ ]
                [ Heading.h2 [ ]
                    [ str "SAFE Template" ] ] ]

          Container.container []
              [ Content.content [ Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ] ]
                    [ Heading.h3 [] [ str ("Press buttons to manipulate counter: " + show model) ] ]
                Columns.columns []
                    [ Column.column [] [ button "-" (fun _ -> dispatch Decrement) ]
                      Column.column [] [ button "+" (fun _ -> dispatch Increment) ] ] ]

          Footer.footer [ ]
                [ Content.content [ Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ] ]
                    [ safeComponents ] ] ]
```

While terse, the main problem with this formatting is that it is exceedingly hard to refactor and move things around. You inevitably move opening or closing brackets around, and then it's quite a lot of work trying to figure out the correct matching order again. With more lengthy examples, it can also become hard to see where things begin and end.

We propose the following formatting instead:

```fsharp
div [] [ 
     Navbar.navbar [ Navbar.Color IsPrimary ] [ 
         Navbar.Item.div [] [ 
              Heading.h2 [] [ str "SAFE Template" ] 
         ] 
     ]

     Container.container [] [ 
         Content.content [ 
              Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ] 
         ] [ 
             Heading.h3 [] [ 
                str ("Press buttons to manipulate counter: " + show model) ]
            ]
            Columns.columns [] [ 
                Column.column [] [ button "-" (fun _ -> dispatch Decrement) ]
                Column.column [] [ button "+" (fun _ -> dispatch Increment) ]
            ] 
         ]
     ] 

     Footer.footer [] [ 
          Content.content  [ 
               Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ] 
          ] [ safeComponents ] 
     ] 
]
```
The main virtues of this scheme is that it's easy to block copy and paste elements around, and that it approximately mimics how  raw HTML (yuck) is often formatted (at least by vim). 

(*) Me and my colleagues.

**Comment by kerams** [comment] 2019-07-10 14:49
Almost just like I format it. A yay from me.

>it's quite a lot of work trying to figure out the correct matching order again. With more lengthy examples, it can also become hard to see where things begin and end.

Absolutely.

**Comment by theimowski** [comment] 2019-07-11 11:18
I believe this has been a debate among Fable programmers for a long time now. 
Would like to bring @MangelMaxime and @Zaid-Ajaj to the discussion - curious to hear their arguments

**Comment by MangelMaxime** [comment] 2019-07-11 12:53
All I am saying here is in good faith. Please don't feel attack or anything like that, I prefer to mention that fact because in the past discussion about formatting tended to be really animated :)

*Disclaimer, the second snippets provided by @juselius doesn't compile so I adapted the code in order to have everything going under the `div` children*

----------

The first snippet is more or less my way of writing views. It was designed when I was learning/discovering F# and indentation based language so it has several problems that you already mentioned. Not easy to move code around, having a lot of keyboard manipulation to do etc.

But it had the benefit of being consistent, compact and make your eyes always read from left to right. It was easy to distinguish props scope from children scope.

----------

The second snippet is a way of writing code that has been proposed several times indeed but I personally was never convinced by it. My main issue with it is that I can't easily see the scope of each block.

I personally have a hard time reading this section, I don't easily see where the properties end and where the children start.

<img width="742" alt="image" src="https://user-images.githubusercontent.com/4760796/61049749-8ecabb80-a3e5-11e9-9edf-089b1d57f8bb.png">

If I schematize what my eyes are doing I got this.

To find `children of Navbar.navbar`:

1. Find `Navbar.navbar`
2. Find the next "indented block". 
3. It's `Navbar.Item.div [] [`, wait it's not a child.
4. Perfect I found it

To find the `children of Content.content`, it gives:

1. Find `Content.content`
2. Find the next "indented block". 
3. It's `Content.Modifiers`, wait it's not a child.
4. Go to the open `[` of `Content.content props`
5. Find the closing brackets `]`
6. Find the next `[`
7. Good I just found the children of `Content.content`

I suppose not everyone has this way of thinking when reading this code. But it shows that there is a big difference in representation between both blocks.

------------------

I am currently working on a set of consistent rules for F# which aims to solve the issues you raised 
above (and more) and make it easy to move around a section of the code because everything is aligned on multiple of the indentation size.

My set of rules is still a WIP and I am currently testing them against a complete application example because we can't take decision based on a single snippet. We can always make it appear good on a small bit of code but the reality can be different.

If I apply my set of rules to the snippet provided by @juselius I get this result:

```fs
div []
    [
        Navbar.navbar [ Navbar.Color IsPrimary ]
            [
                Navbar.Item.div []
                    [
                        Heading.h2 []
                            [ str "SAFE Template" ]
                    ]
            ]

        Container.container []
            [
                Content.content
                    [
                        Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ]
                    ]
                    [
                        Heading.h3 []
                            [
                                str ("Press buttons to manipulate counter: " + show model)
                            ]
                    ]
                Columns.columns []
                    [
                        Column.column [] [ button "-" (fun _ -> dispatch Decrement) ]
                        Column.column [] [ button "+" (fun _ -> dispatch Increment) ]
                    ]
            ]

        Footer.footer []
            [
                Content.content
                    [
                        Content.Modifiers [ Modifier.TextAlignment (Screen.All, TextAlignment.Centered) ]
                    ]
                    [ safeComponents ]
            ]
    ]
```

Yes, it's taking more vertical space but I think it's easy to see the different blocks/scopes.

Another way to visualize the blocks/scopes is to `blur` the code.

On the left @juselius second snippet and on the right my proposed solution.

<img width="1596" alt="Capture d’écran 2019-07-11 à 14 36 53" src="https://user-images.githubusercontent.com/4760796/61051564-98562280-a3e9-11e9-83bf-be606eb25429.png">

**Comment by juselius** [comment] 2019-07-12 09:18
When we are developing UI:s, the code is getting modified, refactored, changed, copied, moved, pasted _all_ the time. It's super important to easily and quickly be able to pick the snippets you need.

I think your new suggestions for formatting are great! Much better than my suggestions. It's better to sacrifice compactness for readability 99% of the time, and your example code is very readable.  When you have been staring at your screen for 10 h, it really counts. 

Upvote 💯!

_Sorry @MangelMaxime for not providing code which compiles 😧 (I wrote the post on a machine without a compiler (sic!).)_

**Comment by MangelMaxime** [comment] 2019-07-12 09:24
> Sorry @MangelMaxime for not providing code which compiles 😧 (I wrote the post on a machine without a compiler (sic!).)

Don't worry :) I prefered to mention it if someone saw the difference or tried your code too.

**Comment by theimowski** [comment] 2019-07-12 11:21
Thanks @MangelMaxime - I like the new proposed formatting, in fact it goes in pair with [F# code formatting guidelines](https://docs.microsoft.com/en-us/dotnet/fsharp/style-guide/formatting#formatting-lists-and-arrays)

**Comment by bast** [comment] 2019-07-12 12:58
I am only starting to learn F# and I admit that I had a hard time reading the "old"/current formatting but really like the proposed new formatting.

**Comment by isaacabraham** [comment] 2019-07-16 08:15
I personally prefer @juselius format - indeed, that's essentially the format we use:

For short / few attributes / props :

```fsharp
dev [ prop1; prop2 ] [ // simple props on same line
    child [] [
        grandchild1 [] [] // empty items on the same line
        grandchild2 [] [
            elem1
            elem2
        ]
    ]
]
```

The closing brace is always vertically aligned with the element, which means vertical guides line up nicely and it's easy to see when you're missing a brace. It doesn't waste a lot of space, is relatively easy on the eye IMHO and doesn't cause the code to "expand" horizontally.

For more than just a few attributes (or if it's simply not appropriate to keep them on a single line), I usually do this:

```fsharp
dev [
    prop1
    prop2 ] [
    child [] [
        grandchild [] [ ]
    ]
]
```

I'm not entirely happy with this as it's not easy to see where attributes stop and child elements start, but it's (IMHO) reasonable. Alternative was

```fsharp
dev [ prop1
      prop2 ] [
    child [] [
        grandchild [] [ ]
    ]
]
```

**Comment by Zaid-Ajaj** [comment] 2019-07-16 09:24
No one seems to mention the possibility that you essentially do not need *two* lists to make UI elements, although we have always done that way, it is not necessarily the way forward and I personally prefer the children to be a property of a parent element in this:
```fs
Html.div [ 
  attr.id "main"
  attr.style [ style.margin 5; style.borderRadius 15 ]
  attr.children [
    Html.h1 [ content "Fable react" ]
    Html.h2 [ content "Can be pretty simple" ]
  ]
]
```
No more debates about nesting attributes vs. nesting children! 

This closely follows the API of [fabulous-simple-elements](https://github.com/Zaid-Ajaj/fabulous-simple-elements) where the module tells you can use without naming collisions. 

We have always used DU for attributes and styles but they come very short because of the overloaded nature of the style, so something like `style.margin` is actually a static overloaded function that either takes a string like `20px` or an integer but not any generic `obj` like they are doing now

**Comment by MangelMaxime** [comment] 2019-07-16 10:34
> No one seems to mention the possibility that you essentially do not need two lists to make UI elements

Indeed, but that's because we are following the HTML/React semantics on this point.

> We have always used DU for attributes and styles but they come very short because of the overloaded nature of the style, so something like style.margin is actually a static overloaded function that either takes a string like 20px or an integer but not any generic obj like they are doing now

I think it's possible to still solve this problem by using DUs but using an interface+helpers to type the expected types.

But we need to be careful to not increase the bundle size too much. 

> This closely follows the API of fabulous-simple-elements where the module tells you can use without naming collisions.

This is close to what Fulma does where everything related to Bulma is actually typed or same for Fable.ReactLeaft bindings.

IHMO, I think it's impossible to have people agree 100% on syntax or DSL API and we need to leave with that too. There will always be pros and cons for one or another solution.

If people want to create a new DSL they can do it of course but it needs to be compatible with the current API which should be simple for React just emit a `ReactElement` or something like that.

**Comment by isaacabraham** [comment] 2019-07-22 08:27
I'm curious to see where @Zaid-Ajaj goes with the DSL he's looking at, but for now I'd be keen to work up two or three alternative versions of a non-trivial piece of code with some different guidelines and see how they shape up. This is [one](https://github.com/CompositionalIT/safe-search/blob/master/src/Client/View.fs) that I can think of. I was using Fantomas with it but it proved to not give great results for Elmish views.

I'd be happy to rewrite this using the style I've suggested above as a PR, and for other people to do the same - we can compare and contrast them all that way?

**Comment by Zaid-Ajaj** [comment] 2019-07-22 10:54
>  I was using Fantomas with it but it proved to not give great results for Elmish views.

Not great is an understatement: my eyes hurt! 

The DSL I am working on is for the base react elements and Fulma doesn't follow that format (yet?) but that code needs a proper clean up: don't define values *inside* the definitions of the children, it's really weird to build giant UIs like that. You can break it down in smaller functions

**Comment by isaacabraham** [comment] 2019-07-22 11:19
@Zaid-Ajaj Yes, I know we can use smaller functions thank you :-) Cleaning up that code is besides the point of this issue though - we're just focusing on layout of F# view really.

Of course, feel free to submit a PR to clean that code up to your satisfaction  ;-)

**Comment by Zaid-Ajaj** [comment] 2019-07-22 11:55
@isaacabraham You can start using [Feliz](https://github.com/Zaid-Ajaj/Feliz) right away if you want to see how things work, it is quite usable now, I am only adding *a lot* of the css/style stuff and shaving off as much as possible of the bundle size (with help of @MangelMaxime)

The only stuff missing now would be the svg elements/attributes and a bunch of style attributes but those could be amended using `style.custom`

**Comment by MangelMaxime** [comment] 2019-07-22 13:18
> Yes, I know we can use smaller functions thank you :-) Cleaning up that code is besides the point of this issue though - we're just focusing on layout of F# view really.

Yes, but if we base  the analysis on a non recommended way to write code it will be biased :)

**Comment by isaacabraham** [comment] 2019-07-22 15:14
@MangelMaxime Think of what's in that file as "raw materials" that you can shape and design as you see fit ;-) I don't mind moving stuff into smaller functions - it was pulled together quickly and looks especially bad because of fantomas - but I think focusing on the look of the layout for a larger piece of elmish code is worthwhile?

**Comment by MangelMaxime** [comment] 2019-07-22 21:28
> but I think focusing on the look of the layout for a larger piece of elmish code is worthwhile?

@isaacabraham Sure I do agree

**Comment by zanaptak** [comment] 2019-08-08 17:33
I don't know the status of this but I went ahead and formatted the OP snippet in [Feliz](https://github.com/Zaid-Ajaj/Feliz) style and two other theoretical variations in case anyone is interested: https://gist.github.com/zanaptak/4e8de186f9f4c31cd4edd457b4fde88d

**Comment by juselius** [comment] 2019-08-15 14:03
I have been on vacation and offline for the past month, but it's nice to see such a good discussion.  @zanaptak The inverse Feliz style (2) is very readable, compact and nice!

**Comment by theprash** [comment] 2020-02-13 15:57
Let's stay on topic now. Alternative DSLs are another discussion.

I think this is a good suggestion and we should go ahead with it. For me, it makes UI code slightly easier to read and **much** easier to write/refactor. I've been writing F# for years in the old style and it's been fine but when using it for UI code I get consistently tangled in unbalanced brackets, wasting a lot of time.

It seems that only @MangelMaxime doesn't like the style. I'm not sure if I agree with the criticisms, but I do accept there are potential downsides. But even then, on balance I think people agree that the upsides outweigh the downsides.

Let's make the change now. @demirtasdev would like to contribute a PR.

**Comment by theimowski** [comment] 2020-02-14 13:49
In long term ideally I'd like the convention to adhere to Fantomas formatting rules so that we can have an "industry standard"

**Comment by theprash** [comment] 2020-02-14 14:15
For reference, this is what Fantomas does to the original example code:

```fsharp
div []
    [ Navbar.navbar [ Navbar.Color IsPrimary ] [ Navbar.Item.div [] [ Heading.h2 [] [ str "SAFE Template" ] ] ]

      Container.container []
          [ Content.content [ Content.Modifiers [ Modifier.TextAlignment(Screen.All, TextAlignment.Centered) ] ]
                [ Heading.h3 [] [ str ("Press buttons to manipulate counter: " + show model) ] ]
            Columns.columns []
                [ Column.column [] [ button "-" (fun _ -> dispatch Decrement) ]
                  Column.column [] [ button "+" (fun _ -> dispatch Increment) ] ] ]

      Footer.footer []
          [ Content.content [ Content.Modifiers [ Modifier.TextAlignment(Screen.All, TextAlignment.Centered) ] ]
                [ safeComponents ] ] ]
```

This is essentially the current scheme used by the template except that it moves more code onto singe lines. I personally would not use Fantomas until it lets me preserve line breaks.

To me, code formatting is too much of an art in F# (perhaps unfortunately) to be constrained by a fixed set of rules that can't take human factors into account, e.g. "this should go on its own line because it's very important to the business logic".

**Comment by juselius** [comment] 2020-02-14 14:35
@theimowski @theprash I think Fantomas should adhere to our wishes and needs, not the other way around. I totally agree that it would be nice with a "industry standard", but I doubt we well ever agree. Personally I think Fantomas way of formatting is not very attractive in general. 

We did some experiments in my group with Fable/Fulma formatting, and tested the new suggested formatting by @MangelMaxime. We pretty quickly decided to go back to the original, as suggested at the top of this thread.

**Comment by Zaid-Ajaj** [comment] 2020-02-14 14:42
> I think Fantomas should adhere to our wishes and needs

@juselius Sounds like a great opportunity to contribute to Fantomas by making list formatting behavior configurable to match those needs.

**Comment by theimowski** [comment] 2020-02-14 14:44
What I'm trying to say is that I'd like to get to a point where one doesn't need to worry about the formatting at all because Fantomas auto format on file save will do it auto magically.
This doesn't possibly mean that writing Fable React code needs to follow the *default* Fantomas configuration, but instead would be great if one could configure Fantomas so that it formats Fable React code up to one's will.

**Comment by juselius** [comment] 2020-02-14 14:49
@Zaid-Ajaj Absolutely!

**Comment by theimowski** [comment] 2021-06-28 17:25
Fantomas is now included and recommended to format your code as part of SAFE v3

**Closed by theimowski** 2021-06-28 17:25 UTC
Labels: Type: Discussion
