### ISSUE TITLE
Azure deployment not working OOTB

### ISSUE THREAD

**Issue by theimowski** [SAFE-Stack/SAFE-template#326] opened 2019-12-19 13:00 UTC
Using latest v1.19 with `--deploy azure`, after `fake build -t appservice` when opening the app in browser following 500 HTTP Error is displayed:

![image](https://user-images.githubusercontent.com/5909015/71175435-d6dcec80-2267-11ea-9d9d-93295e680b27.png)

**Comment by markCompostional** [comment] 2019-12-20 14:02
Hello, have you used a previous version that has worked. I've deployed the default safe template app into azure, and it works for me.
If you repeat the process now, does it work for you? (maybe something was going on on azure)

**Comment by markCompostional** [comment] 2019-12-20 14:31
I DID have to set 
allowPublicClient = true
in the application registration manifest to get the app to deploy, not sure if that could be the source of your issue.

**Comment by theimowski** [comment] 2019-12-20 15:45
Still same issue after redeploying. Where do I set the `allowPublicClient` config?

**Comment by markCompostional** [comment] 2019-12-21 10:25
As I say, I published the standard safe template, and I had an error actually publishing which I resolved by setting allowPublicClient= true in the "manifest" under the "app registration" in the azure portal, it may not be related to your issue.

**Comment by markCompostional** [comment] 2019-12-23 10:10
I'll try to update the documentation on Friday, some of the azure screenshots etc are a bit out of date, and I'll document the allowPublicClient issue.

**Comment by marcpiechura** [comment] 2019-12-23 12:20
I've the same issue and it's not related to the SAFE template, Saturn is the root problem. 
I've used the C# VS Asp.Net Core template and was able to publish an run it without any problems, after adding Saturn to the project and republishing it, the same 500.30 error occurred. The problem is probably that Saturn installs a lot of V2 AspNetCore dependencies: 

![image](https://user-images.githubusercontent.com/6583600/71357699-da81b380-2586-11ea-9a3e-23c95a418ea7.png)

**Comment by Alkasai** [comment] 2020-01-06 01:56
Any updates on this?
I'm trying to run `fake build --target appservice -e subscriptionId=.... -e clientId=....` but it fails.

I get `Finished (Failed) 'ArmTemplate'`
And this error:
```
AdalServiceException: AADSTS50059: No tenant-identifying information found in either 
the request or implied by any provided credentials.
```

**Comment by theimowski** [comment] 2020-01-07 13:40
@Alkasai  I think your issue is related to https://github.com/SAFE-Stack/docs/pull/126 - @isaacabraham is there anything preventing from getting that PR merged?

**Comment by theimowski** [comment] 2020-01-07 14:10
Thanks @marcpiechura, indeed it seems to be a problem with Saturn - it works fine for bare Giraffe (`--server giraffe --deploy azure`) 

Saturn has following deps:
```
   Saturn (0.10)
      FSharp.Control.Websockets (>= 0.2)
      FSharp.Core (>= 4.2.3)
      Giraffe (>= 4.0 < 5.0)
      Microsoft.AspNetCore (>= 2.2)
      Microsoft.AspNetCore.Antiforgery (>= 2.2)
      Microsoft.AspNetCore.Authentication.Cookies (>= 2.2)
      Microsoft.AspNetCore.Authentication.JwtBearer (>= 2.2)
      Microsoft.AspNetCore.Authentication.OAuth (>= 2.2)
      Microsoft.AspNetCore.Authorization (>= 2.2)
      Microsoft.AspNetCore.Cors (>= 2.2)
      Microsoft.AspNetCore.ResponseCompression (>= 2.2)
      Microsoft.AspNetCore.Rewrite (>= 2.2)
      Microsoft.AspNetCore.Session (>= 2.2)
      Microsoft.AspNetCore.StaticFiles (>= 2.2)
      Microsoft.AspNetCore.WebSockets (>= 2.2)
      Microsoft.Extensions.Caching.Memory (>= 2.2)
      System.Threading.Tasks.Dataflow (>= 4.9)
```

Maybe it's one of the `Microsoft.AspNetCore` packages that's causing the issue? 

Giraffe itself doesn't seem to refer to those packages:

```
    Giraffe (4.0.1)
      FSharp.Core (>= 4.7)
      Microsoft.IO.RecyclableMemoryStream (>= 1.2.2)
      Newtonsoft.Json (>= 12.0.2)
      System.Text.RegularExpressions (>= 4.3.1)
      System.ValueTuple (>= 4.5)
      System.Xml.XmlSerializer (>= 4.3)
      TaskBuilder.fs (>= 2.1)
      Utf8Json (>= 1.3.7
```

@Krzysztof-Cieslak

**Comment by isaacabraham** [comment] 2020-01-26 18:47
@markCompostional you got this to work eventually didn't you? Which suggests that the problem isn't Saturn per se but something about the process.

**Comment by isaacabraham** [comment] 2020-01-26 18:47
@theimowski that PR is now merged in as well.

**Comment by theimowski** [comment] 2020-01-28 13:51
IMO the problem is in https://github.com/SaturnFramework/Saturn/issues/214 - I had similar issue for my pet project where I used old version of Giraffe, and after update to netcore3.1 it worked only when I removed `Microsoft.AspNetCore` from `paket.dependencies`

**Comment by jltrem** [comment] 2020-02-01 06:53
I also have the 500.30 error when trying to start in Azure.  No errors during deployment.  I've tried going to netcoreapp3.1 and pinning Saturn to 0.10.1 (hoping that SaturnFramework/Saturn#215 would take care of it).

**Comment by jltrem** [comment] 2020-02-01 21:32
Today's Saturn release SaturnFramework/Saturn/releases/tag/0.11.0 fix the problem for me.  Thanks Chet & Krzysztof!

**Closed** 2020-02-04 15:51 UTC
