### ISSUE TITLE
Include paket.lock file?

### ISSUE THREAD

**Issue by isaacabraham** [SAFE-Stack/SAFE-template#66] opened 2018-04-26 17:41 UTC
Given that we're now including a `yarn.lock` file, shouldn't we do the same with `paket.lock`? Not only will this increase the speed for the first build (important IMHO), but will also allow us to ensure stable releases.

**Comment by Krzysztof-Cieslak** [comment] 2018-04-26 18:07
Uhh, we don’t do that? Yeah, we definitely should, IMO

**Comment by theimowski** [comment] 2018-05-01 09:53
Yep I think the advantage of fast first build doesn't outgrow the cost of having unused dependencies in the project. Closing for now

**Comment by theimowski** [comment] 2018-06-19 09:50
reopening - it's getting more and more irritating, specially since stuff like https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/965 happens and one cannot have deterministic build when creating from given version of template...
@matthid suggested using groups for this, that could work but would require quite a lot of effort

**Comment by supertom44** [comment] 2018-06-19 13:16
I just came to create a new project from the template and got caught out by the above-linked error.

Is there a quick workaround while the issue is being resolved?

Cheers.

**Comment by isaacabraham** [comment] 2018-06-24 15:36
@theimowski how about a compromise here - let's either create a paket lock for when the default options only are selected. Otherwise, it doesn't create one. OR - we create a massive lock file that contains everything for all packages (this potentially introduces other problems though).

I demoed creating a SAFE app from scratch the other night and had to pre-generate the lock file because it simply took too long otherwise.

**Comment by forki** [comment] 2018-06-24 15:37
Yes lock file for default seems a good solution

Isaac Abraham <notifications@github.com> schrieb am So., 24. Juni 2018,
17:36:

**Comment by isaacabraham** [comment] 2018-06-24 21:33
I've just tested out with a clean safe template and included a ready-made paket.lock, it definitely helps a lot. The biggest slow downs that I saw now are (I think) compilation of the javascript side and also this "linking" process of the yarn dependencies. Is there any way that we can "precompute" that as well?

**Comment by forki** [comment] 2018-06-25 07:11
Yes if we add a paket.lock then we should add yarn's lock file as well.

Isaac Abraham <notifications@github.com> schrieb am So., 24. Juni 2018,
23:33:

**Comment by isaacabraham** [comment] 2018-06-25 07:52
The lock file is already there.

**Comment by isaacabraham** [comment] 2018-06-25 21:16
@forki this is what I'm referring to https://github.com/yarnpkg/yarn/issues/1496

**Comment by forki** [comment] 2018-06-26 05:18
I don't think I have this issue.

Isaac Abraham <notifications@github.com> schrieb am Mo., 25. Juni 2018,
23:16:

**Comment by theimowski** [comment] 2018-06-26 17:48
#109 solves the issue partially, I'll keep it open until we have a consistent solution for all possible options

**Comment by theimowski** [comment] 2018-08-08 12:26
Please review #139

**Comment by theimowski** [comment] 2018-08-10 12:14
Should be resolved by #139 now

**Closed by theimowski** 2018-08-10 12:14 UTC
Labels: Status: In Progress, Type: Enhancement
